db:
  labels:
    app: db
    env: dev
    stack: wordpress
  image:
    repository: mariadb
    tag: latest
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: dev
  containerPorts:
      mysql: 3306
